# -*- coding: utf-8 -*-
"""PotholeDetection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pN75FMLp7jgnrdNoXW-ELzE9cd5cMKrB
"""

from google.colab import drive 
drive.mount('/content/drive')

!git clone 'https://github.com/pjreddie/darknet.git' '/content/drive/My Drive/PotholeDetection/Darknet'

# Commented out IPython magic to ensure Python compatibility.
# %cd '/content/drive/My Drive/PotholeDetection/Darknet/'
#!python test_train_data_setup.py
!ls
!wget https://pjreddie.com/media/files/yolov3.weights

# Commented out IPython magic to ensure Python compatibility.
# %cd '/content/drive/My Drive/PotholeDetection/Darknet/'
!sed -i 's/OPENCV=1/OPENCV=0/' Makefile
!sed -i 's/GPU=1/GPU=0/' Makefile
!sed -i 's/CUDNN=1/CUDNN=0/' Makefile

# Commented out IPython magic to ensure Python compatibility.
# %cd '/content/drive/My Drive/PotholeDetection/'
!unzip 100-dataset.zip -d Darknet/data/

# Commented out IPython magic to ensure Python compatibility.
# %cd '/content/drive/My Drive/PotholeDetection/Darknet/'

!python data/test_train_data_setup.py

# Commented out IPython magic to ensure Python compatibility.
# %cd '/content/drive/My Drive/PotholeDetection/Darknet/'
!make

# Commented out IPython magic to ensure Python compatibility.
# %cd '/content/drive/My Drive/PotholeDetection/Darknet/'
!chmod +x darknet

!sudo apt install dos2unix
!dos2unix ./cfg/train_images.txt
!dos2unix ./cfg/test_images.txt
!dos2unix ./cfg/obj.data
!dos2unix ./cfg/obj.names
!dos2unix ./cfg/obj.cfg

# Commented out IPython magic to ensure Python compatibility.
# %cd '/content/drive/My Drive/PotholeDetection/Darknet/'
!./darknet detector train cfg/obj.data cfg/obj.cfg yolov3.weights -dont_show -clear 1